### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: 

### ISSUE THREAD

**Issue by jusitnboggs** [MinecraftModDevelopmentMods/MMDLib#41]
Not sure if I should also post this over at Tcon or not but here we go.

Minecraft crashes while loading.

https://pastebin.com/Z1HY7KWU

**Comment by dshadowwolf** [comment]
see #23 - I had thought this resolved, so...

**Comment by dshadowwolf** [comment]
Okay, seems it is a load-ordering issue - likely resolved in local, will wait to close this until -rc3 and a confirmation its not occurring any longer.

**Comment by LDAsuku** [comment]
I think the issue is Base Minerals. All the other MMD mods (Base/Nether/End/Modern Metals) have been updated to -rc2, but Base Minerals is still -rc1. Removing Base Minerals fixed the problem for me.

**Comment by dshadowwolf** [comment]
...okay, I thought we'd updated it, seems it was missed, somehow - give me a few and I'll fix that.

**Comment by dshadowwolf** [comment]
Okay, update for BaseMinerals pushed out - real fix is to handle load-ordering properly, though (that's queued for MMDLib -rc3) - will close if you confirm updating BaseMinerals works.

**Comment by LDAsuku** [comment]
The issue doesn't seem to be resolved. But after further inspection, the issue is beyond just BaseMinerals. [I'm still getting this crash](https://paste.dimdev.org/afigihiwob.mccrash), but the game starts up fine if I remove one of either AE2, Construct's Armory, or BaseMetals, the first two of which I'm assuming are totally unrelated. So it must be a load-ordering issue, like you said?

Edit: That's the wrong crash report. [Here's the real one.](https://paste.dimdev.org/zaqofokaku.mccrash)

**Comment by YaibaToKen** [comment]
I can confirm it's a load order issue, caused by MMDLib loading before ConArm and trying to use the stats ConArm adds before these being registered.

**Comment by MxtressMyxx** [comment]
I too am getting this error as of today. Disabling the integration with tcon/conarm via config seems to be the only fix until rc3, I assume? (this works - mostly just leaving this comment to sub to the thread for updates on the fix)

**Comment by dshadowwolf** [comment]
Sorry folks, been quite busy doing work I'm being paid for or there would probably have been an -rc3 that fixed this and several other issues.

**Comment by MxtressMyxx** [comment]
> Sorry folks, been quite busy doing work I'm being paid for or there would probably have been an -rc3 that fixed this and several other issues.

No worries! I have a workaround for now - ores are obtainable but tinker/conarm integrations are disabled. I'm just subscribed to remind myself to re-enable when this updates.

Thanks for your efforts.

**Comment by YaibaToKen** [comment]
Ok so... MMDLib is attempting to register armor part stats before ConArm registers them... This might be caused due to our listeners being called before ConArm's... No way to know till I dig a bit deeper in our code, which I'm hoping to do next week, as real life demands aren't in my favour right now.

**Comment by dshadowwolf** [comment]
It is a load-order thing - There is a simple change that I think is already queued for the next release
